export const platforms = [
	"PC",
	"PlayStation 1",
	"PlayStation 2",
	"PlayStation 3",
	"PlayStation 4",
	"PlayStation 5",
	"Nintendo NES",
	"Nintendo SNES",
	"Nintendo 64",
	"Nintendo GameCube",
	"Nintendo Wii",
	"Nintendo WiiU",
	"Nintendo Game Boy",
	"Nintendo Game Boy Color",
	"Nintendo Game Boy Advance",
	"Nintendo DS",
	"Nintendo DSi",
	"Nintendo 3DS",
	"Nintendo New 3DS",
	"Nintendo Switch",
	"Sega Master System",
	"Sega Mega Drive",
	"Sega Game Gear",
	"Xbox",
	"Xbox 360",
	"Xbox One",
	"Xbox Series",
] as const;

export const techPlatforms = [
	...platforms,
	"Nintendo NES Classic",
	"Nintendo SNES Classic",
	"Nintendo GameCube Game Boy Player",
	"Nintendo Wii VC",
	"Nintendo WiiU VC",
	"Nintendo 3DS VC",
	"Nintendo Switch NSO",
] as const;

