export const events = [
	{
		name: "Past Testing Event 20XX",
		shortname: "PTE20XX",
		startDate: "2021-12-13T00:00:00Z",
		endDate: "2021-12-17T16:45:00Z",
		raised: 12345.67,
		eventTimezone: "Australia/Adelaide",
		scheduleReleased: true,
		published: true,
	},
	{
		name: "Future Testing Event 20XX",
		shortname: "FTE20XX",
		startDate: "2026-01-21T23:00:00Z",
		endDate: "2026-01-26T07:00:00Z",
		eventTimezone: "Australia/Perth",
		acceptingSubmissions: true,
		acceptingBackups: true,
		acceptingVolunteers: true,
		scheduleReleased: false,
		published: true,
	},
	{
		name: "Live Testing Event 20XX",
		shortname: "LTE20XX",
		startDate: "2025-07-08T14:00:00Z",
		endDate: "2025-07-13T05:25:00Z",
		eventTimezone: "Australia/Melbourne",
		scheduleReleased: true,
		published: true,
	}
];

export const images_files = [
	{
		list: "Event",
		id: { shortname: "PTE20XX" },
		key: "logo",
		file: "/images/PTE Logo.png"
	},
	{
		list: "Event",
		id: { shortname: "PTE20XX" },
		key: "darkModeLogo",
		file: "/images/PTE Logo Dark.png"
	},
	{
		list: "Event",
		id: { shortname: "PTE20XX" },
		key: "heroImage",
		file: "/images/PTE Hero.png"
	},
	{
		list: "Event",
		id: { shortname: "PTE20XX" },
		key: "ogImage",
		file: "/images/PTE OG Image.png"
	},
	{
		list: "Event",
		id: { shortname: "PTE20XX" },
		key: "postEventBackground",
		file: "/images/PTE Post Event Background.png"
	},
	{
		list: "Event",
		id: { shortname: "LTE20XX" },
		key: "logo",
		file: "/images/LTE Logo.png"
	},
	{
		list: "Event",
		id: { shortname: "LTE20XX" },
		key: "ogImage",
		file: "/images/LTE OG Image.png"
	},
	{
		list: "Event",
		id: { shortname: "FTE20XX" },
		key: "logo",
		file: "/images/FTE Logo.png"
	},
	{
		list: "Event",
		id: { shortname: "FTE20XX" },
		key: "ogImage",
		file: "/images/FTE OG Image.png"
	},
];

export const roles = [
	{
		name: "PTE20XX Runner",
		admin: false,
		canManageContent: false,
		canManageUsers: false,
		event: "PTE20XX",
		show: true,
		colour: "#ff0000",
		textColour: "white",
		runner: true,
		volunteer: false
	},
	{
		name: "PTE20XX Volunteer",
		admin: false,
		canManageContent: false,
		canManageUsers: false,
		event: "PTE20XX",
		show: true,
		colour: "#ff0000",
		textColour: "white",
		runner: false,
		volunteer: true
	},
	{
		name: "Coordinator",
		admin: false,
		canManageContent: true,
		canManageUsers: true,
		event: null,
		show: true,
		colour: "#cc7722",
		textColour: "white",
		runner: false,
		volunteer: false
	}
];

export const users = [
	{
		name: "Genetic Lifeform and Disk Operating System",
		username: "GLaDOS",
		email: "glados@example.com",
		password: "123456789",
		dateOfBirth: "1983-09-06T09:05:46Z",
		pronouns: "She/Her",
		verified: true,
		state: "wa",
		discord: "GLaDOS#0001",
		twitch: "GLaDOS",
		twitter: "Neurotoxin"
	},
	{
		name: "Chell [REDACTED]",
		username: "Chell",
		email: "chell@example.com",
		password: "123456789",
		dateOfBirth: "1997-07-09T08:53:39Z",
		pronouns: "She/Her",
		verified: true,
		state: "vic",
		discord: "Chell#0001",
	},
	{
		name: "Orange",
		username: "P-body",
		email: "pbody@example.com",
		password: "123456789",
		dateOfBirth: "2000-04-02T09:08:18Z",
		verified: true,
		state: "nsw",
		discord: "TallBot#0550",
		twitch: "PBody",
	},
	{
		name: "Blue",
		username: "ATLAS",
		email: "atlas@example.com",
		password: "123456789",
		dateOfBirth: "2000-04-01T09:06:24Z",
		verified: true,
		state: "nsw",
		discord: "Atlas#0009",
		twitter: "WeightOfTheWorld"
	},
	{
		name: "Intelligence Dampening Sphere",
		username: "Wheatley",
		email: "wheatley@example.com",
		password: "123456789",
		dateOfBirth: "1965-08-18T09:09:36Z",
		pronouns: "He/Him",
		verified: false,
		state: "qld",
		discord: "Wheatley#1337",
		twitch: "xX_Wheatley_Xx",
		twitter: "TheSmartestCore"
	}
];

export const runs = [
	{
		game: "Setup Buffer",
		category: "?",
		platform: "?",
		estimate: "12:25:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "AusSpeedruns",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T23:45:00Z"
	},
	{
		game: "Setup Buffer",
		category: "?",
		platform: "?",
		estimate: "12:15:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "AusSpeedruns",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T01:35:00Z"
	},
	{
		game: "Setup Buffer",
		category: "?",
		platform: "?",
		estimate: "12:20:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "AusSpeedruns",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T05:55:00Z"
	},
	{
		game: "A Hat in Time",
		category: "All Time Pieces (All DLC no RW)",
		platform: "PC",
		estimate: "2:10:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T00:20:00Z"
	},
	{
		game: "Peter Jackson's King Kong: The Official Game of the Movie",
		category: "any%",
		platform: "Xbox 360",
		estimate: "2:15:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T06:25:00Z"
	},
	{
		game: "Hollow Knight",
		category: "any% No Major Glitches",
		platform: "PC",
		estimate: "12:45:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-08T21:50:00Z"
	},
	{
		game: "Prey (2017)",
		category: "any%",
		platform: "PC",
		estimate: "12:20:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-08T22:45:00Z"
	},
	{
		game: "Kingdom Hearts: Chain of Memories",
		category: "Riku's Story",
		platform: "GBA",
		estimate: "1:40:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-08T17:10:00Z"
	},
	{
		game: "Kingdom Hearts II Final Mix",
		category: "Critical any% (gummi skip)",
		platform: "PC",
		estimate: "2:40:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: true,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-08T19:00:00Z"
	},
	{
		game: "Bomberman 64",
		category: "any%",
		platform: "Nintendo 64",
		estimate: "12:30:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-08T23:15:00Z"
	},
	{
		game: "Setup Buffer",
		category: "?",
		platform: "?",
		estimate: "12:25:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "AusSpeedruns",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T22:45:00Z"
	},
	{
		game: "Finish / Goodbye",
		category: "?",
		platform: "?",
		estimate: "12:05:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "AusSpeedruns",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-13T05:20:00Z"
	},
	{
		game: "Middle-Earth: Shadow Of Mordor",
		category: "any%",
		platform: "PC",
		estimate: "2:05:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T08:50:00Z"
	},
	{
		game: "Spyro: Year of the Dragon",
		category: "100 egg",
		platform: "PlayStation 1",
		estimate: "1:05:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T16:20:00Z"
	},
	{
		game: "Spy vs. Spy (2005)",
		category: "Story any%",
		platform: "Xbox",
		estimate: "12:35:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T13:00:00Z"
	},
	{
		game: "Shantae Half-Genie Hero",
		category: "Pirate Queen's Quest 100%",
		platform: "PC",
		estimate: "1:00:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T01:15:00Z"
	},
	{
		game: "The Legend of Zelda: Ocarina of Time Master Quest",
		category: "Child Dungeons (No SRM)",
		platform: "Wii Virtual Console",
		estimate: "12:40:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T02:00:00Z"
	},
	{
		game: "The Legend of Zelda: Twilight Princess",
		category: "any%",
		platform: "Nintendo Gamecube",
		estimate: "3:10:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T05:05:00Z"
	},
	{
		game: "Fatal Frame 2: Crimson Butterfly",
		category: "any% NG Normal (PS2)",
		platform: "PlayStation 3",
		estimate: "1:50:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T11:40:00Z"
	},
	{
		game: "Lego Star Wars: The Complete Saga",
		category: "any%",
		platform: "PC",
		estimate: "3:35:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T02:40:00Z"
	},
	{
		game: "Super Mario 3D Land",
		category: "any%",
		platform: "Nintendo 3DS",
		estimate: "1:15:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T02:50:00Z"
	},
	{
		game: "The Elder Scrolls V: Skyrim",
		category: "Marriage ***(BONUS RUN)***",
		platform: "PC",
		estimate: "12:10:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T00:00:00Z"
	},
	{
		game: "Silent Hill",
		category: "any%",
		platform: "PlayStation 1",
		estimate: "1:10:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T02:25:00Z"
	},
	{
		game: "The Elder Scrolls 3: Morrowind",
		category: "any%",
		platform: "PC",
		estimate: "12:20:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T21:40:00Z"
	},
	{
		game: "Final Fantasy 7 Remake Intergrade",
		category: "Yuffie Normal any%",
		platform: "PlayStation 5",
		estimate: "12:55:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T15:40:00Z"
	},
	{
		game: "Final Fantasy VII",
		category: "No Slots",
		platform: "PlayStation 1",
		estimate: "7:05:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T08:25:00Z"
	},
	{
		game: "Spyro: Year of the Dragon (Reignited)",
		category: "any%",
		platform: "PC",
		estimate: "1:15:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T16:45:00Z"
	},
	{
		game: "The Elder Scrolls V: Skyrim",
		category: "Glitchless Main Quest",
		platform: "PC",
		estimate: "1:40:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T22:10:00Z"
	},
	{
		game: "Middle-Earth: Shadow Of War",
		category: "Demo% ***(BONUS RUN)***",
		platform: "PC",
		estimate: "12:20:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T11:05:00Z"
	},
	{
		game: "Silent Hill 4: The Room",
		category: "NG Easy",
		platform: "PC",
		estimate: "1:10:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T03:45:00Z"
	},
	{
		game: "Blinx 2: Masters of Time and Space",
		category: "any%",
		platform: "Xbox",
		estimate: "1:40:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T20:00:00Z"
	},
	{
		game: "Super Mario Bros 3",
		category: "Warpless",
		platform: "NES",
		estimate: "1:00:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T17:35:00Z"
	},
	{
		game: "James Bond 007 Nightfire",
		category: "All Tokens",
		platform: "Nintendo Gamecube",
		estimate: "1:00:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T11:35:00Z"
	},
	{
		game: "Kingdom Hearts 1.5",
		category: "Beginner any%",
		platform: "PlayStation 4",
		estimate: "3:00:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: true,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-08T14:00:00Z"
	},
	{
		game: "Crash Bandicoot 4: It's About Time",
		category: "All Flashback Tapes - Sapphire",
		platform: "PC",
		estimate: "12:25:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T23:10:00Z"
	},
	{
		game: "Donkey Kong Country",
		category: "All Stages",
		platform: "SNES",
		estimate: "12:40:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T13:45:00Z"
	},
	{
		game: "James Bond 007 Nightfire",
		category: "Drake% ***(BONUS RUN)***",
		platform: "Nintendo Gamecube",
		estimate: "12:05:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T12:45:00Z"
	},
	{
		game: "Crash Bandicoot (N-Sane)",
		category: "any%",
		platform: "PC",
		estimate: "1:10:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T21:50:00Z"
	},
	{
		game: "Final Fantasy X-2",
		category: "JP any%",
		platform: "PlayStation 2",
		estimate: "3:35:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T07:55:00Z"
	},
	{
		game: "Xenoblade Chronicles: Future Connected",
		category: "All Ponspectors - Casual",
		platform: "Nintendo Switch",
		estimate: "1:05:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T00:20:00Z"
	},
	{
		game: "Metroid Dread",
		category: "Boss Rush Showcase ***(BONUS RUN)***",
		platform: "Nintendo Switch",
		estimate: "12:15:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T15:40:00Z"
	},
	{
		game: "The World's Hardest Game 3",
		category: "any%",
		platform: "?",
		estimate: "12:40:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T23:55:00Z"
	},
	{
		game: "Blinx: The Time Sweeper",
		category: "any%",
		platform: "Xbox Series S",
		estimate: "1:05:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T18:45:00Z"
	},
	{
		game: "Harry Potter and the Chamber of Secrets",
		category: "Glitchless",
		platform: "PC",
		estimate: "12:55:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T22:50:00Z"
	},
	{
		game: "Golden Sun",
		category: "any% - No Save and Quit",
		platform: "WiiU (VC)",
		estimate: "3:35:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T12:30:00Z"
	},
	{
		game: "Mario Golf World Tour",
		category: "All Courses (No DLC)",
		platform: "Nintendo 3DS",
		estimate: "1:00:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T17:05:00Z"
	},
	{
		game: "Spyro the Dragon",
		category: "120%",
		platform: "PlayStation 2",
		estimate: "1:35:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-09T14:35:00Z"
	},
	{
		game: "Sonic the Hedgehog (Master System)",
		category: "Beat the Game",
		platform: "Master System",
		estimate: "12:25:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T23:20:00Z"
	},
	{
		game: "Jak 3",
		category: "any% Hero Mode",
		platform: "PlayStation 2",
		estimate: "12:20:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T22:15:00Z"
	},
	{
		game: "Prototype",
		category: "Any% (Easy Mode)",
		platform: "PC",
		estimate: "2:15:00 AM",
		finalTime: "2:09:41",
		donationIncentive: "",
		race: false,
		racer: "DaMidget2000",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=PVPVwIY3YMQ",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T21:10:00Z"
	},
	{
		game: "Smile For Me",
		category: "22 Happy Habititians - Good Ending",
		platform: "PC",
		estimate: "12:40:00 AM",
		finalTime: "38:16",
		donationIncentive: "",
		race: false,
		racer: "Noops",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=cz81zIgScEs",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T00:10:00Z"
	},
	{
		game: "Bioshock 2: Minerva's Den",
		category: "Glitchless",
		platform: "PC",
		estimate: "12:25:00 AM",
		finalTime: "22:15",
		donationIncentive: "",
		race: false,
		racer: "Benedictatorr",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=-Sk6nTTesnk",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T15:05:00Z"
	},
	{
		game: "Phonics Racing Adventure",
		category: "Out of Bounds",
		platform: "PC",
		estimate: "12:15:00 AM",
		finalTime: "11:07",
		donationIncentive: "",
		race: false,
		racer: "InputEvelution",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=Ck_iXV4ICrQ",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T12:00:00Z"
	},
	{
		game: "Mike Tyson's Punch-Out!!",
		category: "Blindfolded + One Hand",
		platform: "Nintendo Entertainment System (NES)",
		estimate: "12:45:00 AM",
		finalTime: "38:15",
		donationIncentive: "",
		race: false,
		racer: "mPap",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=GnSkIIRBpRY",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T09:45:00Z"
	},
	{
		game: "Resident Evil 2 (1998)",
		category: "Claire B",
		platform: "PC",
		estimate: "1:00:00 AM",
		finalTime: "56:38",
		donationIncentive: "",
		race: false,
		racer: "MangoPunch",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=fiupwpVTlF0",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T03:00:00Z"
	},
	{
		game: "Alex Rider: Stormbreaker",
		category: "any% (Normal)",
		platform: "Nintendo DS",
		estimate: "1:00:00 AM",
		finalTime: "54:57",
		donationIncentive: "",
		race: false,
		racer: "AeonFrodo",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=x0mXnQDK7S4",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T15:50:00Z"
	},
	{
		game: "Call of Duty Modern Warfare 2",
		category: "Any%",
		platform: "PC",
		estimate: "1:45:00 AM",
		finalTime: "1:31:52",
		donationIncentive: "",
		race: false,
		racer: "Callmeliam",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=hJQzgYyGT8U",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T20:45:00Z"
	},
	{
		game: "The Legend of Zelda: Link's Awakening",
		category: "Any% Glitchless",
		platform: "Nintendo Switch",
		estimate: "2:10:00 AM",
		finalTime: "2:04:36",
		donationIncentive: "",
		race: false,
		racer: "some_random_npc",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=bT-DWR3_Eik",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T08:25:00Z"
	},
	{
		game: "Fantasy Zone",
		category: "Master System Bosses",
		platform: "Nintendo Switch",
		estimate: "12:15:00 AM",
		finalTime: "10:56",
		donationIncentive: "",
		race: false,
		racer: "Hans 'Pichy' Stockmann",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=XJBGVGgxmgw",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T14:35:00Z"
	},
	{
		game: "Dustforce DX",
		category: "16 Red Keys",
		platform: "PC",
		estimate: "1:25:00 AM",
		finalTime: "1:07:22",
		donationIncentive: "",
		race: false,
		racer: "SRLGrace",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=FUTnVBvWR0M",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T23:35:00Z"
	},
	{
		game: "Croc 2",
		category: "Any%",
		platform: "PC",
		estimate: "1:10:00 AM",
		finalTime: "1:03:48",
		donationIncentive: "",
		race: false,
		racer: "Paulmall",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=sU5ZXJKfmhA",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T08:55:00Z"
	},
	{
		game: "Shantae and the Seven Sirens",
		category: "Any%",
		platform: "PC",
		estimate: "2:05:00 AM",
		finalTime: "2:01:58",
		donationIncentive: "",
		race: false,
		racer: "megaslayer321a",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=Pj_4nHJjFqo",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T17:50:00Z"
	},
	{
		game: "Untitled Goose Game",
		category: "100%",
		platform: "PC",
		estimate: "12:35:00 AM",
		finalTime: "34:49",
		donationIncentive: "",
		race: false,
		racer: "Alecat",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=7yDWAw1xXJk",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T13:15:00Z"
	},
	{
		game: "Kingdom Hearts 0.2",
		category: "Beginner any%",
		platform: "PC",
		estimate: "12:30:00 AM",
		finalTime: "24:39",
		donationIncentive: "",
		race: false,
		racer: "FireStriker",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=0gH0ETNZ4g0",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T03:55:00Z"
	},
	{
		game: "Tony Hawk's Pro Skater 3",
		category: "All Goals & Golds",
		platform: "PC",
		estimate: "12:15:00 AM",
		finalTime: "11:38",
		donationIncentive: "",
		race: false,
		racer: "nase",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=mdANDIUleG4",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T07:15:00Z"
	},
	{
		game: "The Simpsons Game",
		category: "NG+ Any%",
		platform: "Xbox 360",
		estimate: "1:00:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T21:40:00Z"
	},
	{
		game: "Pokemon Heart Gold",
		category: "any% Manipless",
		platform: "?",
		estimate: "2:40:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T17:00:00Z"
	},
	{
		game: "Setup Buffer",
		category: "?",
		platform: "?",
		estimate: "12:15:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "AusSpeedruns",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-08T23:55:00Z"
	},
	{
		game: "Digimon World",
		category: "100 Prosperity (Glitched)",
		platform: "PlayStation 2",
		estimate: "1:45:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T06:25:00Z"
	},
	{
		game: "Ecco Jr",
		category: "Easy",
		platform: "PC",
		estimate: "12:10:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T18:45:00Z"
	},
	{
		game: "Celeste",
		category: "All Red Berries",
		platform: "PC",
		estimate: "1:20:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-13T03:50:00Z"
	},
	{
		game: "Hollow Knight",
		category: "All Skills No Major Glitches",
		platform: "PC",
		estimate: "1:10:00 AM",
		finalTime: "1:05:22",
		donationIncentive: "",
		race: false,
		racer: "ins0mnia",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=DWSnbP2kB58",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T05:05:00Z"
	},
	{
		game: "The World's Hardest Game",
		category: "Any% Classic",
		platform: "PC",
		estimate: "12:10:00 AM",
		finalTime: "7:09",
		donationIncentive: "",
		race: false,
		racer: "hsblue",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=E7qBqzk6fKE",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T16:10:00Z"
	},
	{
		game: "Outlast",
		category: "any%",
		platform: "PC",
		estimate: "12:25:00 AM",
		finalTime: "9:46",
		donationIncentive: "",
		race: false,
		racer: "jymmyboiSR",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=0ENPwSxgFnU",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T07:40:00Z"
	},
	{
		game: "Jak and Daxter: The Precursor Legacy",
		category: "100%",
		platform: "PlayStation 2",
		estimate: "1:55:00 AM",
		finalTime: "1:42:06",
		donationIncentive: "",
		race: false,
		racer: "hsblue",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=av4aOq_TDX4",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T04:30:00Z"
	},
	{
		game: "Amnesia: Justine",
		category: "any%",
		platform: "PC",
		estimate: "12:15:00 AM",
		finalTime: "7:26",
		donationIncentive: "",
		race: false,
		racer: "jymmyboi",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=2GJngEF7EOQ",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T08:00:00Z"
	},
	{
		game: "VVVVVV",
		category: "any%",
		platform: "PC",
		estimate: "12:25:00 AM",
		finalTime: "26:41",
		donationIncentive: "",
		race: false,
		racer: "Aytoms",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=uGdKQQFUxes",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T10:45:00Z"
	},
	{
		game: "Sonic the Hedgehog 2",
		category: "Sonic: Beat the Game",
		platform: "Android",
		estimate: "12:30:00 AM",
		finalTime: "23:36",
		donationIncentive: "",
		race: false,
		racer: "werster",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=-E6By9B8FSE",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T05:35:00Z"
	},
	{
		game: "Tomba!/Tombi!",
		category: "All Events",
		platform: "Playstation Portable",
		estimate: "1:35:00 AM",
		finalTime: "1:26:43",
		donationIncentive: "",
		race: false,
		racer: "Raikou",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=riXv8MQyl80",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T01:10:00Z"
	},
	{
		game: "P.N.03",
		category: "Any%",
		platform: "Gamecube",
		estimate: "1:00:00 AM",
		finalTime: "53:18",
		donationIncentive: "",
		race: false,
		racer: "Nicosar",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=bpmRDXbUTco",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T15:00:00Z"
	},
	{
		game: "Spyro the Dragon (Reignited)",
		category: "Any% No Balloonist Skip",
		platform: "PC",
		estimate: "12:55:00 AM",
		finalTime: "50:18",
		donationIncentive: "",
		race: false,
		racer: "Mage",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=hzI0isDfKV8",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T07:05:00Z"
	},
	{
		game: "Super Monkey Ball",
		category: "Master",
		platform: "Gamecube",
		estimate: "12:20:00 AM",
		finalTime: "18:50",
		donationIncentive: "",
		race: false,
		racer: "Barhunga",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=VbKZTx96rdU",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T15:40:00Z"
	},
	{
		game: "Crash Bandicoot (N-Sane Trilogy)",
		category: "Any%",
		platform: "PC",
		estimate: "1:10:00 AM",
		finalTime: "57:55",
		donationIncentive: "",
		race: false,
		racer: "Clockdistrict",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=Nou98_C2ZqE",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T00:00:00Z"
	},
	{
		game: "Diablo III: Reaper of Souls",
		category: "Any% New Game (Monk)",
		platform: "PC",
		estimate: "1:50:00 AM",
		finalTime: "1:40:08",
		donationIncentive: "",
		race: true,
		racer: "meatr0o vs Heckson",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=rYSocU5Nxy4",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T11:45:00Z"
	},
	{
		game: "Spyro the Dragon: Year of the Dragon (Reignited)",
		category: "Any%",
		platform: "PC",
		estimate: "1:15:00 AM",
		finalTime: "1:04:57",
		donationIncentive: "",
		race: true,
		racer: "Bored_Banana vs TheSirBorris",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=vv49v8u7Av8",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T08:15:00Z"
	},
	{
		game: "Super Mario 64",
		category: "120 star",
		platform: "Nintendo 64",
		estimate: "1:50:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T01:50:00Z"
	},
	{
		game: "Middle-Earth: Shadow of War",
		category: "Any%",
		platform: "PC",
		estimate: "3:10:00 AM",
		finalTime: "3:14:43",
		donationIncentive: "",
		race: false,
		racer: "RykonGamingAU",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=LvGEClLB_iE",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T12:50:00Z"
	},
	{
		game: "Spyro 2: Ripto's Rage",
		category: "?",
		platform: "?",
		estimate: "1:45:00 AM",
		finalTime: "1:40:21",
		donationIncentive: "",
		race: false,
		racer: "Dactyly",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=2pR2tqVMQXc",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T08:10:00Z"
	},
	{
		game: "Blinx: The Time Sweeper ",
		category: "Any%",
		platform: "Xbox Series S ",
		estimate: "1:15:00 AM",
		finalTime: "1:07:56",
		donationIncentive: "",
		race: false,
		racer: "Miku",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=Z0XAWU2e_m4",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T18:00:00Z"
	},
	{
		game: "Jak II",
		category: "?",
		platform: "?",
		estimate: "1:15:00 AM",
		finalTime: "1:11:42",
		donationIncentive: "",
		race: false,
		racer: "stylonide",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=yf9oo_ToJ-g",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T06:35:00Z"
	},
	{
		game: "Grand Theft Auto V",
		category: "All Stunt Jumps",
		platform: "PC",
		estimate: "12:50:00 AM",
		finalTime: "46:42",
		donationIncentive: "",
		race: false,
		racer: "nase",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=uxdjvXD6K74",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T17:00:00Z"
	},
	{
		game: "Need For Speed Most Wanted (2005)",
		category: "Any%",
		platform: "PC",
		estimate: "4:25:00 AM",
		finalTime: "4:20:08",
		donationIncentive: "",
		race: false,
		racer: "Psycho",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=1uZvrB1Cwnk",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T16:10:00Z"
	},
	{
		game: "Mr. Driller Drill Land",
		category: "Level 1 All",
		platform: "Nintendo Switch",
		estimate: "12:25:00 AM",
		finalTime: "34:05",
		donationIncentive: "",
		race: false,
		racer: "Hans 'Pichy' Stockmann",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=iff3Vmbms2s",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T14:00:00Z"
	},
	{
		game: "The Legend of Zelda: Ocarina of Time",
		category: "Child Dungeons as Adult",
		platform: "Wii",
		estimate: "1:00:00 AM",
		finalTime: "48:50",
		donationIncentive: "",
		race: false,
		racer: "MikamiHero",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=tEVyxLVy50Y",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T07:45:00Z"
	},
	{
		game: "Tony Hawk's Pro Skater 4",
		category: "Any%",
		platform: "PC",
		estimate: "12:40:00 AM",
		finalTime: "38:56",
		donationIncentive: "",
		race: false,
		racer: "nase",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=Xpy8ghSuTTw",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T06:25:00Z"
	},
	{
		game: "A Hat in Time",
		category: "Any%",
		platform: "PC",
		estimate: "12:50:00 AM",
		finalTime: "45:35",
		donationIncentive: "",
		race: false,
		racer: "Bored_Banana",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=DGXdRN9JBoI",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T02:55:00Z"
	},
	{
		game: "Fire Emblem: Three Houses",
		category: "Crimson Flower - any% NG",
		platform: "Nintendo Switch",
		estimate: "1:40:00 AM",
		finalTime: "1:23:25",
		donationIncentive: "",
		race: false,
		racer: "AeonFrodo",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=L_ggiiG7wGY",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T16:10:00Z"
	},
	{
		game: "Hollow Knight",
		category: "Randomiser True Ending",
		platform: "PC",
		estimate: "3:30:00 AM",
		finalTime: "1:49:02",
		donationIncentive: "",
		race: true,
		racer: "Kenorah vs ins0mnia",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=oBOvAlk7g2o",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T20:10:00Z"
	},
	{
		game: "Metroid Dread",
		category: "any% NMG",
		platform: "Nintendo Switch",
		estimate: "1:50:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T13:40:00Z"
	},
	{
		game: "Big Bass Fishing",
		category: "Arcade any%",
		platform: "?",
		estimate: "12:45:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T16:05:00Z"
	},
	{
		game: "Mario & Sonic at the Olympic Games Tokyo 2020",
		category: "All Events Gold Medals Normal",
		platform: "Nintendo Switch",
		estimate: "12:55:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T11:25:00Z"
	},
	{
		game: "Diddy Kong Racing",
		category: "100%",
		platform: "Nintendo 64",
		estimate: "2:00:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-13T00:20:00Z"
	},
	{
		game: "Sonic the Hedgehog (Master System)",
		category: "TAS Showcase ***(BONUS RUN)***",
		platform: "Master System",
		estimate: "12:15:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T23:55:00Z"
	},
	{
		game: "Tony Hawk's Underground",
		category: "Beginner No Warp",
		platform: "PC",
		estimate: "12:45:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T00:20:00Z"
	},
	{
		game: "Diablo III: Reaper of Souls",
		category: "any% NG (Monk)",
		platform: "PC",
		estimate: "1:50:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T08:20:00Z"
	},
	{
		game: "Skully",
		category: "any%",
		platform: "PC",
		estimate: "1:00:00 AM",
		finalTime: "59:34",
		donationIncentive: "",
		race: false,
		racer: "Duk700",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=sSPnwBUQwZY",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T03:55:00Z"
	},
	{
		game: "Untitled Goose Game",
		category: "any% Glitchless",
		platform: "PC",
		estimate: "12:25:00 AM",
		finalTime: "16:01",
		donationIncentive: "",
		race: false,
		racer: "Alecat",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=eSz37TOZf54",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T05:20:00Z"
	},
	{
		game: "Super Mario Galaxy",
		category: "Any% Luigi",
		platform: "Wii",
		estimate: "2:45:00 AM",
		finalTime: "2:37:07",
		donationIncentive: "",
		race: false,
		racer: "Lachurs",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=pjrWohvzg98",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T21:15:00Z"
	},
	{
		game: "The Simpsons: Hit & Run",
		category: "Better 100%",
		platform: "PC",
		estimate: "3:00:00 AM",
		finalTime: "2:45:14",
		donationIncentive: "",
		race: false,
		racer: "LiquidWiFi",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=uBnW-fwwNUI",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T09:40:00Z"
	},
	{
		game: "Hades",
		category: "One Weapon (Shield)",
		platform: "PC",
		estimate: "12:05:00 AM",
		finalTime: "1:20:34",
		donationIncentive: "",
		race: false,
		racer: "Kenorah",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=ddtQiXBzBbg",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T23:50:00Z"
	},
	{
		game: "Girls Und Panzer: Dream Tank Match",
		category: "Story Mode - Any%",
		platform: "PlayStation 5",
		estimate: "12:40:00 AM",
		finalTime: "37:34",
		donationIncentive: "",
		race: false,
		racer: "Benjlin",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=FIw6Dt2TEjM",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T18:00:00Z"
	},
	{
		game: "Hades",
		category: "3 Weapons",
		platform: "PC",
		estimate: "1:05:00 AM",
		finalTime: "55:45",
		donationIncentive: "",
		race: false,
		racer: "Kenorah",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=oSIjvJhB7X4",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T10:15:00Z"
	},
	{
		game: "Herc's Adventures",
		category: "Any% Jason",
		platform: "PlayStation 3",
		estimate: "1:10:00 AM",
		finalTime: "1:01:34",
		donationIncentive: "",
		race: false,
		racer: "Firery",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=HuHgJI6aluQ",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T14:50:00Z"
	},
	{
		game: "Super Smash Bros. Ultimate",
		category: "All Challenges: Classic Mode",
		platform: "Nintendo Switch",
		estimate: "12:35:00 AM",
		finalTime: "28:01",
		donationIncentive: "",
		race: false,
		racer: "Arahpthos",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=Mjp44n9ln_w",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T10:40:00Z"
	},
	{
		game: "Pokemon Snap",
		category: "100%",
		platform: "Nintendo 64",
		estimate: "12:35:00 AM",
		finalTime: "38:35",
		donationIncentive: "",
		race: false,
		racer: "Thom",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=n3f-pmsIx7o",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T04:35:00Z"
	},
	{
		game: "A Short Hike",
		category: "All Golden Feathers",
		platform: "PC",
		estimate: "12:15:00 AM",
		finalTime: "14:10",
		donationIncentive: "",
		race: false,
		racer: "Alecat",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=m4elRMzxM4Y",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T05:55:00Z"
	},
	{
		game: "Final Speech",
		category: "Filibuster%",
		platform: "IRL",
		estimate: "12:15:00 AM",
		finalTime: "20:34",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "https://www.twitch.tv/videos/1090896004",
		youtubeVOD: "https://www.youtube.com/watch?v=5XXvB13BraY",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T16:30:00Z",
		runners: ["GLaDOS"]
	},
	{
		game: "Legend of Valkyrie",
		category: "any%",
		platform: "Nintendo Switch",
		estimate: "12:30:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T03:50:00Z"
	},
	{
		game: "The Simpsons: Hit & Run",
		category: "100%",
		platform: "PC",
		estimate: "3:20:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: true,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-10T18:10:00Z"
	},
	{
		game: "VVVVVV",
		category: "any% No OOB",
		platform: "PC",
		estimate: "12:20:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T18:15:00Z"
	},
	{
		game: "Superliminal",
		category: "any% ***(BONUS RUN)***",
		platform: "?",
		estimate: "12:15:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T11:00:00Z"
	},
	{
		game: "Resident Evil 2 (1998)",
		category: "Leon A",
		platform: "PC",
		estimate: "12:55:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T00:45:00Z"
	},
	{
		game: "Jak II",
		category: "any%",
		platform: "PlayStation 2",
		estimate: "1:05:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T21:00:00Z"
	},
	{
		game: "KeyWe",
		category: "any% (Co-Op)",
		platform: "PC",
		estimate: "1:15:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: true,
		racer: "",
		coop: true,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T04:30:00Z"
	},
	{
		game: "Jak and Daxter: The Precursor Legacy",
		category: "100%",
		platform: "?",
		estimate: "1:45:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T19:05:00Z"
	},
	{
		game: "Banjo-Kazooie",
		category: "Any%",
		platform: "Nintendo 64",
		estimate: "1:20:00 AM",
		finalTime: "1:06:09",
		donationIncentive: "",
		race: false,
		racer: "The8bitbeast",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=a0ZNQMTjBeU",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T01:00:00Z"
	},
	{
		game: "Resident Evil 7 Biohazard",
		category: "NG+ any% Easy",
		platform: "PlayStation 5",
		estimate: "1:50:00 AM",
		finalTime: "1:35:18",
		donationIncentive: "",
		race: false,
		racer: "Catticko",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=mEFreB3eCXc",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T06:20:00Z"
	},
	{
		game: "Resident Evil 3: Nemesis",
		category: "any%",
		platform: "PC",
		estimate: "12:50:00 AM",
		finalTime: "49:42",
		donationIncentive: "",
		race: false,
		racer: "MangoPunch",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=vIISB0W2OyA",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T04:10:00Z"
	},
	{
		game: "Ecco Jr",
		category: "?",
		platform: "?",
		estimate: "12:15:00 AM",
		finalTime: "10:09",
		donationIncentive: "",
		race: false,
		racer: "Mecheon",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=WQVEoiGEPZA",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T11:20:00Z"
	},
	{
		game: "Mario Golf: World Tour",
		category: "any%",
		platform: "3DS",
		estimate: "1:15:00 AM",
		finalTime: "1:14:27",
		donationIncentive: "",
		race: false,
		racer: "JTMagicman",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=oA8JuPqirWo",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T08:20:00Z"
	},
	{
		game: "Sonic Adventure DX",
		category: "Big's Story",
		platform: "?",
		estimate: "12:20:00 AM",
		finalTime: "9:44",
		donationIncentive: "",
		race: false,
		racer: "stylonide",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=QxUgGPR04vU",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T11:30:00Z"
	},
	{
		game: "Ratchet & Clank: Into the Nexus",
		category: "NG+",
		platform: "PS3",
		estimate: "12:25:00 AM",
		finalTime: "23:04",
		donationIncentive: "",
		race: false,
		racer: "mobius",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=-vUjLV6ZvQM",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T11:35:00Z"
	},
	{
		game: "Resident Evil 2 Remake",
		category: "Leon A Standard 60FPS",
		platform: "?",
		estimate: "1:00:00 AM",
		finalTime: "59:30",
		donationIncentive: "",
		race: false,
		racer: "tim_trollgasm",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=rZsvfMouRxg",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T05:10:00Z"
	},
	{
		game: "Futurama",
		category: "any%",
		platform: "Xbox",
		estimate: "12:55:00 AM",
		finalTime: "52:56",
		donationIncentive: "",
		race: false,
		racer: "stylonide",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=MHJ9RXJ2cZs",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T20:05:00Z"
	},
	{
		game: "Crash Bandicoot 2: Cortex Strikes Back",
		category: "100%",
		platform: "PlayStation 2",
		estimate: "1:25:00 AM",
		finalTime: "1:13:05",
		donationIncentive: "",
		race: true,
		racer: "Rexaaayyy vs Rab",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=y1yuRgvj_SY",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T01:20:00Z"
	},
	{
		game: "Splatoon 2 - Octo Expansion",
		category: "any% - No Game Over Abuse",
		platform: "Nintendo Switch",
		estimate: "1:20:00 AM",
		finalTime: "1:20:35",
		donationIncentive: "",
		race: true,
		racer: "Duk700 vs AeonFrodo",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=OjaWwM9rpSM",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T06:15:00Z"
	},
	{
		game: "Grand Theft Auto: Vice City",
		category: "any% (No SSU)",
		platform: "PC",
		estimate: "1:10:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T19:50:00Z"
	},
	{
		game: "Superliminal",
		category: "Glitchless",
		platform: "PC",
		estimate: "12:30:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T10:20:00Z"
	},
	{
		game: "Time Crisis 3",
		category: "any% Very Hard",
		platform: "?",
		estimate: "12:40:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-12T16:15:00Z"
	},
	{
		game: "Half-life 2",
		category: "any% no voidclip",
		platform: "PC",
		estimate: "1:10:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-13T02:30:00Z"
	},
	{
		game: "Kirby's Dream Land",
		category: "Normal Mode",
		platform: "3DS Virtual Console",
		estimate: "12:20:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T21:10:00Z"
	},
	{
		game: "DOOM Eternal",
		category: "100% Nightmare",
		platform: "PC",
		estimate: "2:55:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T04:15:00Z"
	},
	{
		game: "Kena Bridge of Spirits",
		category: "any% (Unrestricted)",
		platform: "PlayStation 5",
		estimate: "12:25:00 AM",
		finalTime: "",
		donationIncentive: "",
		race: false,
		racer: "",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "",
		event: "LTE20XX",
		scheduledTime: "2025-07-11T07:20:00Z"
	},
	{
		game: "Blinx 2: Masters of Time and Space",
		category: "Any%",
		platform: "Xbox",
		estimate: "1:40:00 AM",
		finalTime: "1:35:41",
		donationIncentive: "",
		race: false,
		racer: "Aun_El",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=AjocjVa9S4g",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T19:25:00Z"
	},
	{
		game: "Super Mario World",
		category: "In the 6",
		platform: "SNES",
		estimate: "12:15:00 AM",
		finalTime: "8:23",
		donationIncentive: "",
		race: false,
		racer: "Sten",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=wuzlXKex0TQ",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T14:40:00Z"
	},
	{
		game: "Ratchet: Deadlocked",
		category: "any%",
		platform: "PlayStation 3",
		estimate: "1:20:00 AM",
		finalTime: "1:19:08",
		donationIncentive: "",
		race: false,
		racer: "danmcd",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=D90OsSQUxnw",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T10:05:00Z"
	},
	{
		game: "Banjo-Kazooie",
		category: "Glitch Exhibition (TAS)",
		platform: "Nintendo 64",
		estimate: "12:20:00 AM",
		finalTime: "1:06:09",
		donationIncentive: "",
		race: false,
		racer: "The8bitbeast",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=a0ZNQMTjBeU",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T02:30:00Z"
	},
	{
		game: "Fisherman's Bait 2 Big Ol' Bass",
		category: "Any% (Co-op)",
		platform: "PlayStation 1",
		estimate: "12:50:00 AM",
		finalTime: "53:05",
		donationIncentive: "",
		race: false,
		racer: "Rexaaayyy",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=pOysmuZZ508",
		event: "PTE20XX",
		scheduledTime: "2021-12-13T02:55:00Z"
	},
	{
		game: "Pokemon: Lets Go Pikachu",
		category: "any%",
		platform: "Nintendo Switch",
		estimate: "3:15:00 AM",
		finalTime: "3:08:27",
		donationIncentive: "",
		race: false,
		racer: "Aspect",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=F44xGuh3c2o",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T12:25:00Z"
	},
	{
		game: "Star Wars: Empire at War",
		category: "any% (Empire)",
		platform: "PC",
		estimate: "1:10:00 AM",
		finalTime: "1:09:19",
		donationIncentive: "",
		race: false,
		racer: "Benjlin",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=gymU8-IMzYs",
		event: "PTE20XX",
		scheduledTime: "2021-12-14T18:50:00Z"
	},
	{
		game: "Silent Hill 2",
		category: "?",
		platform: "?",
		estimate: "12:55:00 AM",
		finalTime: "53:56",
		donationIncentive: "",
		race: false,
		racer: "jymmyboi",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=RknTK_gn3Q8",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T13:45:00Z"
	},
	{
		game: "Kingdom Hearts 1.5 Final Mix",
		category: "Level 1 Any%",
		platform: "PC",
		estimate: "3:05:00 AM",
		finalTime: "2:49:36",
		donationIncentive: "",
		race: false,
		racer: "Acelord",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=vk8YW3gFlKo",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T22:40:00Z"
	},
	{
		game: "Kingdom Hearts 3",
		category: "Any%",
		platform: "PS5",
		estimate: "3:30:00 AM",
		finalTime: "3:14:45",
		donationIncentive: "",
		race: false,
		racer: "Glint",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=qoSfVNZOTPY",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T01:55:00Z"
	},
	{
		game: "Spyro the Dragon",
		category: "Vortex",
		platform: "PS2",
		estimate: "12:35:00 AM",
		finalTime: "27:53",
		donationIncentive: "",
		race: false,
		racer: "Martyrr",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=TEnkLCBPJK0",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T06:20:00Z"
	},
	{
		game: "Ratchet & Clank: Rift Apart",
		category: "NG+",
		platform: "PlayStation 5",
		estimate: "2:00:00 AM",
		finalTime: "1:38:21",
		donationIncentive: "",
		race: false,
		racer: "mobius",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=N6sBeIhOD9g",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T12:10:00Z"
	},
	{
		game: "Puyo Puyo Tetris",
		category: "Any%",
		platform: "Nintendo Switch",
		estimate: "1:05:00 AM",
		finalTime: "1:01:32",
		donationIncentive: "",
		race: false,
		racer: "Yoshi100_Aus",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=mPqfv2ED6g8",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T12:00:00Z"
	},
	{
		game: "Pokemon Heart Gold",
		category: "Manipless",
		platform: "New 2DS XL",
		estimate: "4:15:00 AM",
		finalTime: "3:56:44",
		donationIncentive: "",
		race: true,
		racer: "JTMagicman vs werster",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=hZ_qxlnXDG8",
		event: "PTE20XX",
		scheduledTime: "2021-12-15T00:05:00Z"
	},
	{
		game: "The Simpsons: Hit & Run",
		category: "All Story Missions",
		platform: "PC",
		estimate: "1:30:00 AM",
		finalTime: "1:28:42",
		donationIncentive: "",
		race: true,
		racer: "AtomicCaleb vs Gordo",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=5aHT-774aq0",
		event: "PTE20XX",
		scheduledTime: "2021-12-16T16:10:00Z"
	},
	{
		game: "Ratchet: Deadlocked",
		category: "NG+ co-op",
		platform: "PlayStation 3",
		estimate: "12:10:00 AM",
		finalTime: "9:49",
		donationIncentive: "",
		race: false,
		racer: "danmcd",
		coop: false,
		twitchVOD: "",
		youtubeVOD: "https://www.youtube.com/watch?v=I9CQXaOHEYw",
		event: "PTE20XX",
		scheduledTime: "2021-12-17T14:20:00Z"
	}
]

export const submissions = [
	{
		runner: 'Chell',
		game: 'Portal',
		category: 'Glitchless',
		platform: 'PC',
		estimate: '01:00:00',
		ageRating: 'm_or_lower',
		donationIncentive: '',
		specialReqs: '',
		availability: [true, true, null, true, true],
		race: 'no',
		coop: false,
		video: 'google.com',
		status: 'accepted',
		event: 'FTE20XX',
		willingBackup: true
	},
	{
		runner: 'Chell',
		game: 'Portal 2',
		category: 'Any%',
		platform: 'PC',
		estimate: '01:20:00',
		ageRating: 'm_or_lower',
		donationIncentive: 'I sing Cara Mia Addio',
		specialReqs: '',
		availability: [true, false, true, false, true],
		race: 'no',
		coop: false,
		video: 'google.com',
		status: 'backup',
		event: 'FTE20XX',
		willingBackup: false
	},
	{
		runner: 'Chell',
		game: 'Portal Stories: Mel',
		category: 'Story Mode Inbounds',
		platform: 'PC',
		estimate: '00:40:00',
		ageRating: 'm_or_lower',
		availability: [false, true, false, true, false],
		race: 'no',
		coop: false,
		video: 'google.com',
		status: 'rejected',
		event: 'FTE20XX',
		willingBackup: false
	},
	{
		runner: 'Chell',
		game: 'Portal Reloaded',
		category: 'No SLA',
		platform: 'PC',
		estimate: '02:15:00',
		ageRating: 'm_or_lower',
		donationIncentive: '',
		specialReqs: 'Must be high fived after every test chamber',
		availability: [false, false, false, false, true],
		race: 'only',
		racer: 'Companion Cube',
		coop: true,
		video: 'google.com',
		status: 'submitted',
		event: 'FTE20XX',
		willingBackup: true
	},
]

export const volunteers = [
	{
		volunteer: 'P-body',
		jobType: 'host',
		eventHostTime: 7,
		maxDailyHostTime: 4,
		dayTimes: ['10 - 6', '10 - 6', '10 - 10', '10 - 6', 'None'],
		specificGame: 'Any',
		specificRunner: 'ATLAS',
		additionalInfo: 'I will speak in bleeps and boops',
		event: 'FTE20XX',
	},
	{
		volunteer: 'P-body',
		jobType: 'social',
		dayTimes: ['All', 'All', 'All', 'All', 'All'],
		experience: 'Casual',
		favMeme: 'christmas tiktok by tagashowie',
		event: 'FTE20XX',
	},
	{
		volunteer: 'P-body',
		jobType: 'runMgmt',
		event: 'FTE20XX',
		runnerManagementAvailability: 'I will not be there for setup but all other days I can be there.'
	},
	{
		volunteer: 'P-body',
		jobType: 'tech',
		techAvailablity: 'I will be there for setup but not the other days.',
		techExperience: 'I am literally a robot',
		event: 'FTE20XX',
	}
];

export const incentives = [
	{
		run: "The Elder Scrolls 3: Morrowind",
		title: "Live any% Tutorial",
		type: "goal",
		data: "{\"goal\": 750, \"current\": 0}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "Hollow Knight",
		title: "Save / Abandon the grub",
		type: "war",
		data: "{\"options\": [{\"name\": \"Save\", \"total\": 0}, {\"name\": \"Abandon\", \"total\": 0}]}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "Crash Bandicoot 4: It's About Time",
		title: "Crash skin selection",
		type: "war",
		data: "{\"options\": [{\"name\": \"General Rule\", \"total\": 0}, {\"name\": \"Mother Clucker\", \"total\": 0}, {\"name\": \"Cats Meow\", \"total\": 0}, {\"name\": \"Warped Biker\", \"total\": 0}]}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "Blinx 2: Masters of Time and Space",
		title: "Name the Time Sweeper",
		type: "war",
		data: "{\"options\": []}",
		active: true,
		event: "LTE20XX",
		notes: "Max 12 characters"
	},
	{
		run: "The Legend of Zelda: Ocarina of Time Master Quest",
		title: "File Name",
		type: "war",
		data: "{\"options\": []}",
		active: true,
		event: "LTE20XX",
		notes: "Max 8 characters"
	},
	{
		run: "Pokemon Heart Gold",
		title: "Player name",
		type: "war",
		data: "{\"options\": []}",
		active: true,
		event: "LTE20XX",
		notes: "Max 7 characters"
	},
	{
		run: "Final Fantasy VII",
		title: "Cloud's Name",
		type: "war",
		data: "{\"options\": []}",
		active: true,
		event: "LTE20XX",
		notes: "Max 9 characters"
	},
	{
		run: "Peter Jackson's King Kong: The Official Game of the Movie",
		title: "Save or Leave Kong ",
		type: "war",
		data: "{\"options\": [{\"name\": \"Save\", \"total\": 0}, {\"name\": \"Leave\", \"total\": 0}]}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "Grand Theft Auto: Vice City",
		title: "Couch completes Autoscrollers",
		type: "goal",
		data: "{\"goal\": 500, \"current\": 0}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "Spy vs. Spy (2005)",
		title: "Spy cosplay on stream",
		type: "goal",
		data: "{\"goal\": 500, \"current\": 0}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "Super Mario 3D Land",
		title: "Special World 8 - Crown",
		type: "goal",
		data: "{\"goal\": 500, \"current\": 0}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "VVVVVV",
		title: "Category Change to 100%",
		type: "goal",
		data: "{\"goal\": 1000, \"current\": 0}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "Big Bass Fishing",
		title: "Language Choice",
		type: "war",
		data: "{\"options\": [{\"name\": \"English\", \"total\": 0}, {\"name\": \"Italian\", \"total\": 0}, {\"name\": \"French\", \"total\": 0}, {\"name\": \"German\", \"total\": 0}]}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "Jak and Daxter: The Precursor Legacy",
		title: "Language Choice",
		type: "war",
		data: "{\"options\": [{\"name\": \"Japanese\", \"total\": 0}, {\"name\": \"German\", \"total\": 0}, {\"name\": \"English\", \"total\": 0}, {\"name\": \"Spanish\", \"total\": 0}]}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "KeyWe",
		title: "Play game in Italian",
		type: "goal",
		data: "{\"goal\": 750, \"current\": 0}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "Time Crisis 3",
		title: "Category Selection",
		type: "war",
		data: "{\"options\": [{\"name\": \"Alan\", \"total\": 0}, {\"name\": \"Wesley\", \"total\": 0}]}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "DOOM Eternal",
		title: "No Frostbomb Trick on Marauder",
		type: "goal",
		data: "{\"goal\": 500, \"current\": 0}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "The World's Hardest Game 3",
		title: "Player Colour",
		type: "war",
		data: "{\"options\": [{\"name\": \"Red\", \"total\": 0}, {\"name\": \"Green\", \"total\": 0}, {\"name\": \"Rainbow\", \"total\": 0}, {\"name\": \"Blue\", \"total\": 0}, {\"name\": \"Yellow\", \"total\": 0}, {\"name\": \"Grey\", \"total\": 0}, {\"name\": \"\", \"total\": 0}]}",
		active: true,
		event: "LTE20XX",
		notes: ""
	},
	{
		run: "The Simpsons: Hit & Run",
		title: "Homer 1 Outfit Choice",
		type: "war",
		data: "{\"options\": [{\"name\": \"Muumuu\", \"total\": 0}, {\"name\": \"Casual\", \"total\": 0}, {\"name\": \"Chosen One\", \"total\": 0}]}",
		active: true,
		event: "LTE20XX",
		notes: "Applies to both racers"
	},
	{
		run: "Silent Hill",
		title: "Ending Choice",
		type: "war",
		data: "{\"options\": [{\"name\": \"Bad Ending\", \"total\": 0}, {\"name\": \"Bad+ Ending\", \"total\": 0}, {\"name\": \"Good Ending\", \"total\": 0}, {\"name\": \"Good+ Ending\", \"total\": 0}, {\"name\": \"UFO Ending\", \"total\": 0}]}",
		active: true,
		event: "LTE20XX",
		notes: "Closes at run start"
	}
]
