-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "darkModeLogo_extension" TEXT,
ADD COLUMN     "darkModeLogo_filesize" INTEGER,
ADD COLUMN     "darkModeLogo_height" INTEGER,
ADD COLUMN     "darkModeLogo_id" TEXT,
ADD COLUMN     "darkModeLogo_width" INTEGER,
ADD COLUMN     "heroImage_extension" TEXT,
ADD COLUMN     "heroImage_filesize" INTEGER,
ADD COLUMN     "heroImage_height" INTEGER,
ADD COLUMN     "heroImage_id" TEXT,
ADD COLUMN     "heroImage_width" INTEGER,
ADD COLUMN     "ogImage_extension" TEXT,
ADD COLUMN     "ogImage_filesize" INTEGER,
ADD COLUMN     "ogImage_height" INTEGER,
ADD COLUMN     "ogImage_id" TEXT,
ADD COLUMN     "ogImage_width" INTEGER,
ADD COLUMN     "postEventBackground_extension" TEXT,
ADD COLUMN     "postEventBackground_filesize" INTEGER,
ADD COLUMN     "postEventBackground_height" INTEGER,
ADD COLUMN     "postEventBackground_id" TEXT,
ADD COLUMN     "postEventBackground_width" INTEGER,
ADD COLUMN     "postEventPage" JSONB NOT NULL DEFAULT '[{"type":"paragraph","children":[{"text":""}]}]';
